### ISSUE TITLE
Cannot Run Dev Locally

### ISSUE THREAD

**Issue by DonaldBough** [JoeRoddy/firestation#27]
Hello,

I recently pulled this onto my Macbook running MacOS Mojave (10.14.6), Node v11.60, npm 3.10.10, and none of the queries are able to run once after the app opens with npm run dev. I have a production version of Firestation downloaded separately, and it works fine.

I went on to delete package.json, change my Node version to v8.5.0, and bump up electron to v2.0.0 but ran into the same issue. After a few hours of trying to get things working I figured I would ask for help. 

- Console warnings after running npm start

```
WARNING in ./~/@google-cloud/firestore/build/src/index.js
[0] Critical dependencies:
[0] 24:19-49 the request of a dependency is an expression
[0]  @ ./~/@google-cloud/firestore/build/src/index.js 24:19-49
[0]
[0] WARNING in ./~/@google-cloud/firestore/build/src/v1beta1/firestore_client.js
[0] Critical dependencies:
[0] 20:16-46 the request of a dependency is an expression
[0]  @ ./~/@google-cloud/firestore/build/src/v1beta1/firestore_client.js 20:16-46
[0]
[0] WARNING in ./~/hash-stream-validation/index.js
[0] Module not found: Error: Cannot resolve module 'fast-crc32c' in /Users/donaldbough/Documents/Source_Code/firestation/node_modules/hash-stream-validation
[0]  @ ./~/hash-stream-validation/index.js 5:8-30
[0]
[0] WARNING in ./~/google-gax/~/grpc/src/grpc_extension.js
[0] Critical dependencies:
[0] 32:12-33 the request of a dependency is an expression
[0]  @ ./~/google-gax/~/grpc/src/grpc_extension.js 32:12-33
[0]
[0] WARNING in ./~/write-file-atomic/index.js
[0] Module not found: Error: Cannot resolve module 'worker_threads' in /Users/donaldbough/Documents/Source_Code/firestation/node_modules/write-file-atomic
[0]  @ ./~/write-file-atomic/index.js 17:24-49
[0]
[0] WARNING in ./~/google-gax/~/grpc/~/node-pre-gyp/lib/pre-binding.js
[0] Critical dependencies:
[0] 20:22-48 the request of a dependency is an expression
[0]  @ ./~/google-gax/~/grpc/~/node-pre-gyp/lib/pre-binding.js 20:22-48
[0]
[0] WARNING in ./~/google-gax/~/grpc/~/node-pre-gyp/lib/util/versioning.js
[0] Critical dependencies:
[0] 17:20-67 the request of a dependency is an expression
[0]  @ ./~/google-gax/~/grpc/~/node-pre-gyp/lib/util/versioning.js 17:20-67
[0]
[0] WARNING in ./~/google-gax/~/grpc/src/node/extension_binary/node-v48-darwin-x64-unknown/grpc_node.node
[0] Module parse failed: /Users/donaldbough/Documents/Source_Code/firestation/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-darwin-x64-unknown/grpc_node.node Unexpected character '�' (1:0)
[0] You may need an appropriate loader to handle this file type.
[0] SyntaxError: Unexpected character '�' (1:0)
[0]     at Parser.pp$4.raise (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
[0]     at Parser.pp$7.getTokenFromCode (/Users/
[0] donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:2756:10)
[0]     at Parser.pp$7.readToken (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:2477:17)
[0]     at Parser.pp$7.nextToken (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:2468:15)
[0]     at Parser.parse (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:515:10)
[0]     at Object.parse (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
[0]     at Parser.parse (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/lib/Parser.js:902:15)
[0]     at DependenciesBlock.<anonymous> (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/lib/NormalModule.js:104:16)
[0]     at DependenciesBlock.onModuleBuild (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
[0]     at nextLoader (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
[0]  @ ./~/google-gax/~/grpc/src ^\.\/.*$
[0]
[0] WARNING in ./~/google-gax/~/grpc/~/node-pre-gyp/lib/util/nw-pre-gyp/index.html
[0] Module parse failed: /Users/donaldbough/Documents/Source_Code/firestation/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util/nw-pre-gyp/index.html Unexpected token (1:0)
[0] You may need an appropriate loader to handle this file type.
[0] SyntaxError: Unexpected token (1:0)
[0]     at Parser.pp$4.raise (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
[0]     at Parser.pp.unexpected (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
[0]     at Parser.pp$3.parseExprAtom (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
[0]     at Parser.pp$3.parseExprSubscripts (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
[0]     at Parser.pp$3.parseMaybeUnary (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
[0]     at Parser.pp$3.parseExprOps (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
[0]     at Parser.pp$3.parseMaybeConditional (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
[0]     at Parser.pp$3.parseMaybeAssign (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
[0]     at Parser.pp$3.parseExpression (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
[0]     at Parser.pp$1.parseStatement (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
[0]  @ ./~/google-gax/~/grpc/~/node-pre-gyp/lib ^\.\/.*$
[0]
[0] WARNING in ./~/google-gax/~/grpc/~/node-pre-gyp/lib/util/compile.js
[0] Module not found: Error: Cannot resolve module 'npm' in /Users/donaldbough/Documents/Source_Code/firestation/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util
[0]  @ ./~/google-gax/~/grpc/~/node-pre-gyp/lib/util/compile.js 39:27-49
[0]
[0] WARNING in ./~/node-gyp/lib/Find-VisualStudio.cs
[0] Module parse failed: /Users/donaldbough/Documents/Source_Code/firestation/node_modules/node-gyp/lib/Find-VisualStudio.cs Unexpected token (9:6)
[0] You may need an appropriate loader to handle this file type.
[0] SyntaxError: Unexpected token (9:6)
[0]     at Parser.pp$4.raise (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
[0]     at Parser.pp.unexpected (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
[0]     at Parser.pp.semicolon (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
[0]     at Parser.pp$1.parseExpressionStatement (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
[0]     at Parser.pp$1.parseStatement (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
[0]     at Parser.pp$1.parseTopLevel (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
[0]     at Parser.parse (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
[0]     at Object.parse (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
[0]     at Parser.parse (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/lib/Parser.js:902:15)
[0]     at DependenciesBlock.<anonymous> (/Users/donaldbough/Documents/Source_Code/firestation/node_modules/webpack/lib/NormalModule.js:104:16)
[0]  @ ./~/node-gyp/lib ^\.\/.*$
[1] objc[33848]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa89623d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11281ff50). One of the two will be used. Which one is undefined.
```

**Comment by JoeRoddy** [comment]
Hey @DonaldBough 

Should've asked, did you try setting up with the `projectRevamp` branch by any chance?  Been doing all my upgrades there:
`git fetch --all`
`get checkout projectRevamp`
`rm -rf node_modules && npm i`
`npm start`

**Comment by DonaldBough** [comment]
Ah I did not. Let me try with that and get back with you. Thanks for the quick response.

**Comment by DonaldBough** [comment]
The dev app works great now. Trying to start with a small change and fixing the icon for Mac, but getting this error while running `npm run release`. I'll try updating electron-builder version later today. Is npm run release the best way to build the full app locally?

`Error: ENOENT: no such file or directory, open '/Users/donaldbough/Documents/Source_Code/firestation/dist/mac/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist'
    at /Users/donaldbough/Documents/Source_Code/firestation/node_modules/electron-builder-lib/src/packager/mac.ts:43:215`

**Comment by JoeRoddy** [comment]
It should be `npm run release`, yeah. I just tried it on linux and that's working ok, so it might be an issue with the Mac setup. (should output to `/dist`)

Can you confirm that you're getting the same error before you add the new icon / without any changes?
