### ISSUE TITLE
Firestore support

### ISSUE THREAD

**Issue by joerozek** [JoeRoddy/firestation#5]
The tool looks great and I would love to use it with Firestore DBs.

**Comment by JoeRoddy** [comment]
Hey Joe, 

I have a prototype working on this branch if you want to try it out:
https://github.com/JoeRoddy/firestation/tree/firestore

(no promises that it will work on your machine though :/ )

It's been a while since I've worked on this project, but if I see that there is more demand for a Firestore version, then I'll definitely get on it and finish it up.

**Comment by joerozek** [comment]
Awesome. It seems to be working so far.  Thanks.  Good luck with Texable.

**Comment by JoeRoddy** [comment]
If you find any specific issues with it (I'm sure there are a ton) feel free to open up an issue on it! Would be helpful :D 

Biggest one atm is that I can't get the new version to package correctly.

**Comment by JoeRoddy** [comment]
I guess I'll just leave this open until we merge in the Firestore branch.

**Comment by danidfm** [comment]
Would be perfect to have firestore as well.

I have done the checkout to the "firestore" branch and I can't still get access to it. I need something else rather than what we have on the instructions?

Thanks!

**Comment by JoeRoddy** [comment]
@danidfm I should've deleted that branch.  I've moved the changes from it to a more stable core electron template.  Checkout this branch: https://github.com/JoeRoddy/firestation/tree/projectRevamp

Then you can just run:
`
$ npm install
$ npm start
`

**Comment by danidfm** [comment]
It works! that's awesome.

Really thanks for this work! it helps a lot! :D

**Comment by JoeRoddy** [comment]
@danidfm Glad to hear it! :D

Let me know if you find any issues at all, or even just suggestions would be great.  I don't actually use Firestore on my own projects, so I just have a basic understanding of how the collections / document structure works.

**Comment by danidfm** [comment]
Sure! 

Will post any issue or idea I could have :)

**Comment by catchshyam** [comment]
Awesome, just what the doctor prescribed. This one can grow to what Robo3T is for MongoDB.

@JoeRoddy any ideas how I can query the sub collections in a document?

**Comment by JoeRoddy** [comment]
That isn't supported quite yet.  How would you expect the query to look if it was supported?

Something like this?
`select * from users.userSubCollection where subCollectionProp = "value";`

I have a feeling ^this kind of thing could be really expensive for the firestore read quota.

Is your goal to sort through ALL sub collections that exist and filter by a prop on the sub-document?  Or to show all documents that belong to filtered parents?  I would guess filtered parents thing will be a lot less expensive, but that's just my intuition, I don't actually use Firestore often.

I'm going to have to re-write the results tree to display documents and collections.  At the moment the results tree has no idea whether it's displaying Firestore results or Realtime, just that it's showing data.

I can work on this^ today and I'll push an update and let you know.  Would you be willing to play with it / provide feedback when you get a chance?

**Comment by catchshyam** [comment]
@JoeRoddy thanks for being so responsive, appreciate it. 

In my db, i have 3 levels of sub collections, and I would want to go to the depth my collections are. For example,

Game (root collection) -> Level (sub collection) -> subLevel (sub collection of level)

How I would like to query?
select * from game.level.subLevel where level.id = "levelId" and subLevel.id = "subLevelId"

In my case, I have embedded the id into my sub collection documents but everyone may not do that (this is not enforced by firestore).

May be I am asking for too much :)

Ofcourse, I will be more than happy to play around and loop you back.

Thanks a ton.

**Comment by JoeRoddy** [comment]
What do you think about this? :

`select level.sublevel from game where level.id = "levelId" and level.subLevel.id = "subLevelId";`

^That should maintain consistency with the realtime queries and generic sql and produce what you want (I think).  I think the props you're filtering by (level.id && level.subLevel.id) should be relative to the collection you're selecting from (game), otherwise it's hard for the application to know "Does he want the level.id of this document? The one two levels beneath it? etc." 

Does that make sense?  I totally understand what you're going for in that query, but I have a feeling it would be pretty hard to implement programatically.

Thanks for the feedback @catchshyam !

**Comment by catchshyam** [comment]
That's perfect and seems consistent with sql syntax (my sql knowledge is poor)

**Comment by fdambrosio** [comment]
awesome! thank you @JoeRoddy the 'projectRevamp' branch works well with Cloud Firestore

**Comment by fdambrosio** [comment]
I'm unable to delete any item

**Comment by JoeRoddy** [comment]
@fdambrosio It's possibly a tweak I made broke the deletes.  I'll take a look at it today.  Can you give me an example delete statement that isn't working for you?

**Comment by JoeRoddy** [comment]
It's working for me at the moment, example of what I ran: 
`delete from users where age > 20;`
or
`delete from collectionName where documentProp (one of > < = != ) someValue;`

Nested deletes inside nested document won't work as of yet.  Still fiddling around with nested docs and seeing if there's a non-horrible way to query them.

**Comment by fdambrosio** [comment]
thank you @JoeRoddy  , this is an example: 

`insert into testapp.example.users.01 (name, level, email) values ('Joe', 99, 'joe@gmail.com');`

`delete from testapp.example.users where level = 99;`

The insert works but with 'delete' when I press 'commit' button there's no changes on firestore database

**Comment by JoeRoddy** [comment]
Okay, I see what you're going for.  I tested it out and got the same result.  It can't delete the item because it doesn't know that the doc exists.  If you do `select * from testapp` , does anything show up for you?  I couldn't get it to, but it did show up on the Firebase console.

I inspected the results data.  It knows that the testapp collection exists, but it couldn't find any documents inside of it.

![image](https://user-images.githubusercontent.com/16690442/38938394-68ed58a4-42f3-11e8-962a-ad26e56d3952.png)

^I think this may give us a clue as to what's going on.  I'm guessing this deep structure isn't really supported the way that it is with the realtime database.  I'm not an expert at all on Firestore, but I would guess you may want to normalize your data, and bring everything up to a root 'users' collection.

**Comment by fdambrosio** [comment]
`select * from testapp.example.users where level = 99;`
this works, so maybe it works only using 'where' ?

**Comment by MiyoAlpizar** [comment]
Hi, this is a great project, i would love to use it, but i get an error when a run npm start:

` ERROR  Failed to compile with 1 errors                                 22:01:18

 error  in ./src/index.js

Syntax Error: Unexpected token (22:7)

  20 | // };
  21 | 
> 22 | render(<App />, document.getElementById("root"));
     |        ^
  23 | `

i don´t know, maybe i am doing somenthig wrong =(

**Comment by JoeRoddy** [comment]
@MiyoAlpizar Did you run `npm install` first?  What operating system are you on?

**Comment by devpascoe** [comment]
hmmm trying to get this running but facing 2 errors
```
error  in ./src/components/App.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
```
and
```
 error  in ./src/stores/Store.js

Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
```
Steps:
i cloned the repo. check out projectRevamp. npm install. npm start.
i'm on a mac running high sierra
node 9.5.0
npm 5.6.0

**Comment by devpascoe** [comment]
anyone else unable to start after an npm update on the projectRevamp branch?

**Comment by JoeRoddy** [comment]
@devpascoe Did a fresh clone and had the same issue.  The decorator fix in the issue you linked fixed it for me.  Do a :
 `git pull`
 `npm i`
 `npm start` 
and let me know if that fixes it for you.

**Comment by JoeRoddy** [comment]
@devpascoe Definitely could be, it uses web storage and it often cant differentiate between different installations. There should be a cache_reset variable in a config file I think. Set that to true and restart the app.

If it starts working, just set it back to false. Let me know if that helps.

**Comment by devpascoe** [comment]
Nar, src/config.js setting
export const CACHE_RESET = true;

npm start gives same error :(

**Comment by devpascoe** [comment]
ok, took a little snooping to get this going but i have something working.
1. update the line in Store.js in setCurrentDatabase(database) from
```
this.currentDatabase.title = database.title;
```
(since ^ this was an initial load and there was no Application Local Storage in the chrome tools)
Changed to:
```
if (database) {
  this.currentDatabase.title = database.title;
}
```
2. I progressed however no commands worked, empty result sets. I noticed in Local Storage the currentDatabase had set "firestoreEnabled":false which it should be true. I'm unsure yet why it thought my security key belonged to Realtime DB instead of Firestore. It is indeed for Firestore.
Reload and tadaa i get data from my firestore db.

**Comment by JoeRoddy** [comment]
@devpascoe lol, I'm glad you got it working. 

When you say your "security key" said firestore, do you mean the service account config thing? It should be the same file for both databases, unless they changed something, which would be bad for this project, hah.

**Comment by devpascoe** [comment]
security key was just a reference to the service account .json file required to connect to the db.

**Comment by bpkennedy** [comment]
I can confirm @devpascoe worked for me, as well.  Thanks!  @JoeRoddy , thank you for making this - it's great!

**Comment by SebScoFr** [comment]
Just expressing my interest for an official Firestore support as well!

**Comment by ksubbu199** [comment]
I am having problem with starting the application on the projectRevamp branch.
Any help would be great :) 

```
 ERROR  Failed to compile with 2 errors                                                                                                11:02:14 PM

 error  in ./src/index.js

Module build failed: Error: Cannot use the decorators and decorators-legacy plugin together
    at validatePlugins (/home/subbu/react/firestation/node_modules/@babel/parser/lib/index.js:10401:13)
    at getParser (/home/subbu/react/firestation/node_modules/@babel/parser/lib/index.js:10464:5)
    at parse (/home/subbu/react/firestation/node_modules/@babel/parser/lib/index.js:10448:12)
    at parser (/home/subbu/react/firestation/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/home/subbu/react/firestation/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/home/subbu/react/firestation/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at runAsync (/home/subbu/react/firestation/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/home/subbu/react/firestation/node_modules/@babel/core/lib/transform.js:34:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 error  in ./src/background.js

Module build failed: Error: Cannot use the decorators and decorators-legacy plugin together
    at validatePlugins (/home/subbu/react/firestation/node_modules/@babel/parser/lib/index.js:10401:13)
    at getParser (/home/subbu/react/firestation/node_modules/@babel/parser/lib/index.js:10464:5)
    at parse (/home/subbu/react/firestation/node_modules/@babel/parser/lib/index.js:10448:12)
    at parser (/home/subbu/react/firestation/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/home/subbu/react/firestation/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/home/subbu/react/firestation/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at runAsync (/home/subbu/react/firestation/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/home/subbu/react/firestation/node_modules/@babel/core/lib/transform.js:34:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 
```

**Comment by fastfedora** [comment]
Adding my support for a Firestore version as well. 

I also wanted to note that I almost dismissed this project as dead, since the last commit is over a year ago and there's nothing in the README about upcoming support for Firestore. It's another 6 months on, and I totally understand not having the time to put into side projects. 

If Firestore still actively being considered, updating the README might generate additional interest. I've been searching and right now I can't find any active GUI consoles for Firestore beyond the default Google console, which is severely limited.

**Comment by JoeRoddy** [comment]
It's a great point @fastfedora , I'll update the readme.

This branch was working pretty well w/ firestore from what I remember, I just got burnt out for a really long time.  I'll try to get a stable release ready so we can merge into master and get the actual app executables published. I may need some help testing the app if anyone is up for it.

**Comment by JoeRoddy** [comment]
If anyone in this thread is a JavaScript dev, I could really use your help testing this library:  https://github.com/JoeRoddy/firebase-sql

I extracted the query translation code into it's own dependency to make it easier to test.  If you're able to try it out and identify any issues, that would really help speed up the release of Firestation w/ Firestore support.

Thanks! -Joe

**Comment by Shoshin23** [comment]
Hi, 

Firstly a really neat project @JoeRoddy. 

I wanted to check if there's a possibility of having querying nested collections added to Firestore support? Or is it already there? 

I'm trying to do something like:
`select * from users where analytics.isUserVerified = false; 
`
The app just stays in processing mode for a really long time and doesn't seem to work. Can you tell me if it's just me or does Firestation currently not supported nested queries. 

thank you!

**Comment by JoeRoddy** [comment]
Hey @Shoshin23, if `analytics` is a nested document, then no, I don't think that query is supported yet.  That would definitely be on the road map, but to be honest, I haven't really felt like there has been much interest in this project lately, so I haven't invested a ton of time into updating it.

If/when I start actively developing Firestation again, that will definitely be a feature I'll try to implement.

**Comment by cakechris** [comment]
Hello @JoeRoddy - I'm afraid to admit that I can't figure out how to "generate new private key". Has the Firebase console interface changed recently? 

Regards,
Chris

**Comment by saket1999** [comment]
Is subcollection query not available yet @JoeRoddy ?

**Comment by smbowler** [comment]
Hello, is there a way to display more than 50 results on a Select * query?
